spring:
  application:
    name: carpooling_swiv
  datasource:
    url: ${url-db-postgres}
    username: ${username-db-postgres}
    password: ${password-db-postgres}
    driver-class-name: org.postgresql.Driver
  cloud:
      azure:
        keyvault:
          secret:
            property-sources[0]:
              endpoint: https://carpoolingvault.vault.azure.net/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
google:
  maps:
    api:
      key: ${api-key-google-maps}
signature:
  secret: ${secret-signature}
