plugins {
    id 'java'
}

allprojects {
    group = 'co.edu.uco'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

subprojects {

    sourceCompatibility = '17'

    apply plugin: 'java'

    tasks.named('test') {
        useJUnitPlatform()
    }

    tasks.register("preparekotlinbuildscriptmodel"){}
}

